// <auto-generated />
using System;
using BibliotecaMovil.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BibliotecaMovil.Server.Migrations
{
    [DbContext(typeof(BibliotecaDbContext))]
    [Migration("20260217230539_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Autor", b =>
                {
                    b.Property<int>("IdAutor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAutor"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAutor");

                    b.ToTable("Autores", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Editorial", b =>
                {
                    b.Property<int>("IdEditorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEditorial"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEditorial");

                    b.ToTable("Editoriales", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Ejemplar", b =>
                {
                    b.Property<int>("IdEjemplar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEjemplar"));

                    b.Property<string>("CodigoInventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEjemplar");

                    b.HasIndex("IdLibro");

                    b.ToTable("Ejemplares", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Favorito", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaAgregado");

                    b.HasKey("IdUsuario", "IdLibro");

                    b.HasIndex("IdLibro");

                    b.ToTable("Favoritos", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Libro", b =>
                {
                    b.Property<int>("IdLibro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLibro"));

                    b.Property<DateTime>("AnioPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AutorIdAutor")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("EditorialIdEditorial")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdEditorial")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resumen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLibro");

                    b.HasIndex("AutorIdAutor");

                    b.HasIndex("CategoriaIdCategoria");

                    b.HasIndex("EditorialIdEditorial");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdEditorial");

                    b.ToTable("Libros", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.LibroAutor", b =>
                {
                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.HasKey("IdLibro", "IdAutor");

                    b.HasIndex("IdAutor");

                    b.ToTable("LibroAutor", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Prestamo", b =>
                {
                    b.Property<int>("IdPrestamo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrestamo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEjemplar")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPrestamo");

                    b.HasIndex("IdEjemplar");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Prestamos", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.PrestamoDetalle", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("EjemplarIdEjemplar")
                        .HasColumnType("int");

                    b.Property<int>("IdEjemplar")
                        .HasColumnType("int");

                    b.Property<int>("IdPrestamo")
                        .HasColumnType("int");

                    b.Property<int?>("PrestamoIdPrestamo")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.HasIndex("EjemplarIdEjemplar");

                    b.HasIndex("PrestamoIdPrestamo");

                    b.ToTable("PrestamoDetalle");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Resena", b =>
                {
                    b.Property<int>("IdResena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdResena"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comentario");

                    b.Property<DateTime>("FechaResena")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaResena");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int")
                        .HasColumnName("IdLibro");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<decimal?>("Puntuacion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Puntuacion");

                    b.HasKey("IdResena");

                    b.HasIndex("IdLibro");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Resenas", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdLibro")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("LibroIdLibro")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("LibroIdLibro");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Reservas", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Sancion", b =>
                {
                    b.Property<int>("IdSancion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSancion"));

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPrestamo")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pagada")
                        .HasColumnType("bit");

                    b.Property<int?>("PrestamoIdPrestamo")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdSancion");

                    b.HasIndex("PrestamoIdPrestamo");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Sanciones", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios", "dbo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Ejemplar", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Libro", "Libro")
                        .WithMany("Ejemplares")
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Favorito", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Libro", "Libro")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMovil.Server.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Libro", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorIdAutor");

                    b.HasOne("BibliotecaMovil.Server.Models.Categoria", null)
                        .WithMany("Libros")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.HasOne("BibliotecaMovil.Server.Models.Editorial", null)
                        .WithMany("Libros")
                        .HasForeignKey("EditorialIdEditorial");

                    b.HasOne("BibliotecaMovil.Server.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMovil.Server.Models.Editorial", "Editorial")
                        .WithMany()
                        .HasForeignKey("IdEditorial")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Categoria");

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.LibroAutor", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Autor", "Autor")
                        .WithMany("LibroAutores")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMovil.Server.Models.Libro", "Libro")
                        .WithMany("LibroAutores")
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Prestamo", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Ejemplar", "Ejemplar")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdEjemplar")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMovil.Server.Models.Usuario", "Usuario")
                        .WithMany("Prestamos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ejemplar");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.PrestamoDetalle", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Ejemplar", "Ejemplar")
                        .WithMany()
                        .HasForeignKey("EjemplarIdEjemplar");

                    b.HasOne("BibliotecaMovil.Server.Models.Prestamo", "Prestamo")
                        .WithMany("Detalles")
                        .HasForeignKey("PrestamoIdPrestamo");

                    b.Navigation("Ejemplar");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Resena", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Libro", "Libro")
                        .WithMany("Resenas")
                        .HasForeignKey("IdLibro")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BibliotecaMovil.Server.Models.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Reserva", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Libro", "Libro")
                        .WithMany("Reservas")
                        .HasForeignKey("LibroIdLibro");

                    b.HasOne("BibliotecaMovil.Server.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Libro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Sancion", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Prestamo", "Prestamo")
                        .WithMany("Sanciones")
                        .HasForeignKey("PrestamoIdPrestamo");

                    b.HasOne("BibliotecaMovil.Server.Models.Usuario", "Usuario")
                        .WithMany("Sanciones")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Prestamo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Usuario", b =>
                {
                    b.HasOne("BibliotecaMovil.Server.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Autor", b =>
                {
                    b.Navigation("LibroAutores");

                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Categoria", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Editorial", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Ejemplar", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Libro", b =>
                {
                    b.Navigation("Ejemplares");

                    b.Navigation("Favoritos");

                    b.Navigation("LibroAutores");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Prestamo", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Sanciones");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BibliotecaMovil.Server.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Prestamos");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");

                    b.Navigation("Sanciones");
                });
#pragma warning restore 612, 618
        }
    }
}
